# Audio-Visual Speaker Detection Configuration
# ===========================================

# Audio Configuration
audio:
  device_index: 0                    # ReSpeaker 8 Mic Array (auto-detected)
  sample_rate: 16000                 # Sample rate in Hz
  n_channels: 8                      # Total channels (8 microphones)
  mic_indexes: [0, 1, 2, 3, 4, 5, 6, 7]  # All 8 microphones on ReSpeaker 8 Mic Array
  frame_samples: 1024                # Analysis window (64 ms @16k)
  hop_samples: 512                   # 50% overlap
  mic_spacing: 0.035                 # Meters between adjacent mics (~3.5 cm)
  sound_speed: 340.0                 # Speed of sound in m/s (matches DOA implementation)
  activity_threshold: 0.003          # Audio activity detection threshold

# Video Configuration
video:
  camera_index: 0                    # Camera device index
  frame_width: 640                   # Frame width in pixels
  frame_height: 480                  # Frame height in pixels
  face_confidence_threshold: 0.7     # Minimum confidence for face detection
  overlap_threshold: 0.3             # NMS overlap threshold
  mouth_open_threshold: 0.02         # Threshold for mouth open detection (0.0-1.0)
  face_detection_skip_frames: 2      # Skip frames for performance optimization

# Detection Parameters
detection:
  speaker_confidence_threshold: 0.3  # Minimum confidence for speaker detection
  angle_offset: 0.0                  # Calibration offset in degrees
  max_faces: 10                      # Maximum number of faces to track

# Microphone Pairs for TDOA calculation
# For 8-mic circular array: opposite pairs (180 degrees apart)
# Mic layout: 0: 0°, 1: 45°, 2: 90°, 3: 135°, 4: 180°, 5: 225°, 6: 270°, 7: 315°
mic_pairs:
  - [0, 4, 0.081]  # Opposite pair: 0° - 180° (diameter)
  - [1, 5, 0.081]  # Opposite pair: 45° - 225°
  - [2, 6, 0.081]  # Opposite pair: 90° - 270°
  - [3, 7, 0.081]  # Opposite pair: 135° - 315°

# Logging Configuration
logging:
  level: INFO                        # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/speaker_detection.log" # Log file path (relative to project root)

# Performance Settings
performance:
  audio_buffer_size: 4               # Audio buffer size for overlap
  face_detection_skip_frames: 2      # Skip frames when no audio activity
  max_processing_time: 0.1           # Maximum processing time per frame (seconds)
